### ISSUE TITLE
Please install a more reliable SSL certificate for https://victi.ms

### ISSUE THREAD

**Issue by volkertb** [victims/victims-enforcer#14]
Currently, the official Victims database at https://victi.ms uses an SSL certificate issued by StartCom. By default, Java does not have the root certificate for this CA included in its Keystore (neither Java 6 nor Java 7), and as a result the victims-enforcer will fail to synchronize with the on-line database. When running mvn with the -e and -X options, the underlying SSLHandshakeException can be seen.

Please replace the SSL certificate with one from a more reputable source. Not just because Java does not have its root certificate bundled in its keystore by default, but also because StartCom is a company that is distrusted by many people. A crucial security service such as the Red Hat Victims database ought to have a solid SSL certificate, preferably an EV certifcate from a more trusted issuer.

Steps to reproduce:

Run mvn clean install or mvn clean package with either the default implied baseUrl, or explicitly with https://victi.ms or https://www.victi.ms as the baseUrl.

Expected behavior:

The victims-enforcer should successfully synchronize with the database.

Actual behavior:

Maven fails with the following message:

[WARNING] Rule 0: com.redhat.victims.VictimsRule failed with message:
Failed to sync database

Workaround:

Configure the non-SSL http://victi.ms as the baseUrl.

Also, I noticed that the Common Name (CN) in the StartCom certificate is "www.victi.ms" (with a www prefix), which appears inconsistent with https://victi.ms, the baseUrl that we are told to use (and which is currently the default, if I'm not mistaken). Browsers don't appear to have an issue with it, but I'm reporting this additional finding anyway.

**Comment by ashcrow** [comment]
Closing out old issues. We have an updated cert not from StartCom now :smile:
