### ISSUE TITLE
Allow scope-level configuration

### ISSUE THREAD

**Issue by dfj** [victims/victims-enforcer#23]
Allow the mode of operation (warning|fatal|disabled) to be configurable based on the dependency scope of the vulnerable artifact. The configuration interface could be implemented a few ways. Off the top of my head, a good way might be to add a "scope" attribute to the "fingerprint" and "metadata" elements. For example, to say that all vulnerable artifacts detected by fingerprint are "fatal" unless they're in the test scope, in which case they are "warning":

```XML
<fingerprint>fatal</fingerprint>
<fingerprint scope="test">warning</fingerprint>
```

i.e. without the scope attribute, the setting applies to all scopes that do not have an explicit setting.

For background:

http://post-office.corp.redhat.com/archives/jboss-integration-platform-developers/2014-May/msg00042.html

**Comment by ashcrow** [comment]
Closing old issues.
