### ISSUE TITLE
Create best practice guidance for configuration of victims-enforcer and modules

### ISSUE THREAD

**Issue by gcmurphy** [victims/victims-enforcer#9]
A project that uses modules and reactor doesn't seem to play well with the enforcer plugin. For example - https://github.com/ryanzhang/jboss-bpm-example-app.

Although I've successfully got enforcer to be invoked for each subproject for Wildfly the project above does not work unless you configure victims for each of the child poms. 

I need to determine why enforcer is not being invoked and make either the corresponding code change or document how to use the plugin with a nested project structure.

**Comment by ashcrow** [comment]
Closing old issues.

**Comment by abn** [comment]
@ashcrow old issues are still issues :) Probably best to leave them open till we figure out what the plan forward is.
